"""empty message

Revision ID: f9ec751f1f3e
Revises: c13da7186876
Create Date: 2025-07-16 22:42:38.607139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ec751f1f3e'
down_revision = 'c13da7186876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
